# Generated by Django 3.0 on 2024-06-02 11:50

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auto_slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='title', unique_with=('sno',)),
            preserve_default=False,
        ),
    ]
